export const SwapStatus = {
    0: 'TxNotStable',
    1: 'TxVerifyFailed',
    3: 'TxWithWrongValue',
    5: 'TxNotSwapped',
    7: 'TxProcessed',
    8: 'MatchTxEmpty',
    9: 'MatchTxNotStable',
    10: 'MatchTxStable',
    12: 'TxWithBigValue',
    14: 'MatchTxFailed',
    15: 'SwapInBlacklist',
    16: 'ManualMakeFail',
    19: 'TxWithWrongPath',
    20: 'MissTokenConfig',
    21: 'NoUnderlyingToken',
    255: 'KeepStatus',
    256: 'Reswapping',
}

export const ChainID = {
    1: "ETH Mainnet",
    5: "GOERLI Mainnet",
    10: "OPTIMISTIC Mainnet",
    25: "CRONOS Mainnet",
    40: "TLOS Mainnet",
    56: "BSC Mainnet",
    57: "SYSCOIN Mainnet",
    66: "OKT Mainnet",
    86: "gatechain Mainnet",
    100: "XDAI Mainnet",
    106: "VELAS Mainnet",
    122: "FUSE Mainnet",
    128: "HECO Mainnet",
    137: "MATIC Mainnet",
    199: "BTT Mainnet",
    250: "FTM Mainnet",
    321: "KCS Mainnet",
    336: "SHI Mainnet",
    592: "ASTAR Mainnet",
    1024: "clover Mainnet",
    1030: "conflux Mainnet",
    1088: "METIS Mainnet",
    1284: "MOONBEAM Mainnet",
    1285: "MOONRIVER Mainnet",
    4689: "IOTEX Mainnet",
    42161: "ARB Mainnet",
    42220: "CELO Mainnet",
    42262: "OASIS Mainnet",
    43114: "AVAX Mainnet",
    32659: "FSN Mainnet",
    1313161554: "AURORA Mainnet",
    1666600000: "HARMONY Mainnet",
}

export default {
    SwapStatus,
    ChainID,
}